#!/bin/bash

LIBDIR=/home/pyronia/libpyronia

cd $LIBDIR/libraries/libapparmor
./autogen.sh
./configure --prefix=/usr --with-perl --with-python
sudo make
sudo make install

cd $LIBDIR/binutils
sudo make
sudo make install

cd $LIBDIR/utils
sudo make
sudo make install

cd $LIBDIR/parser
sudo make
sudo make install

cd $LIBDIR/profiles
sudo make
sudo make install
