#!/bin/bash

LIBDIR=/home/pyronia/libpyronia/libapparmor

cd $LIBDIR/libraries/libapparmor
sudo make clean
./autogen.sh
./configure --prefix=/usr --with-perl --with-python
sudo make
sudo make install

cd $LIBDIR/binutils
sudo make
sudo make install

cd $LIBDIR/utils
sudo make
sudo make install

cd $LIBDIR/parser
make clean
sudo make
sudo make install

cd $LIBDIR/profiles
sudo make
sudo make install
