#!/bin/bash

KERNEL_SRC=/home/pyronia/pyronia-linux
BUILD=/home/pyronia/build/kernel

cd $KERNEL_SRC
echo "======== [x64-kernel] Cleaning build directories. ========"
make O=$BUILD ARCH=x86_64 clean
make O=$BUILD ARCH=x86_64 mrproper
