#!/bin/bash

SRCDIR=$HOME/libpyronia/testsuite

gcc -g $SRCDIR/kernel_upcall_test.c -o $HOME/kernel_upcall_test -lpyronia -lsmv

cd $HOME

echo "*** Running End-to-End Pyronia Tests***"

./kernel_upcall_test
