#!/bin/bash

SRCDIR=$HOME/libpyronia/libsmv/testcases

if [ $# -ne 1 ];
then
    echo "Usage: ./run_smv_tests (0 | 1)"
    exit 0
fi

RUN=$1

if [ $RUN == "0" ];
then

gcc -g $SRCDIR/memdom_ops_tests.c -o $HOME/memdom_ops_test -lsmv
gcc -g $SRCDIR/smv_ops_tests.c -o $HOME/smv_ops_test -lsmv
gcc -g $SRCDIR/smvthread_ops_tests.c -o $HOME/smvthread_ops_test -lsmv -lpthread
gcc -g $SRCDIR/tc_memdom_alloc.c -o $HOME/tc_memdom_alloc_test -lsmv -lpthread
gcc -g $SRCDIR/tc_memdom_create.c -o $HOME/tc_memdom_create_test -lsmv -lpthread
gcc -g $SRCDIR/tc_smv_create.c -o $HOME/tc_smv_create_test -lsmv -lpthread
gcc -g $SRCDIR/tc_smvthread_create.c -o $HOME/tc_smvthread_create_test -lsmv -lpthread
gcc -g $SRCDIR/tc_shared_mm.c -o $HOME/tc_shared_mm_test -lsmv -lpthread
gcc -g $SRCDIR/privs_t1.c -o $HOME/privs_test -lsmv -lpthread
gcc -g $SRCDIR/tc_cond_var.c -o $HOME/tc_cond_var_test -lsmv -lpthread

cd $HOME

echo "*** Running End-to-End SMV Tests***"

./memdom_ops_test
./smv_ops_test
./smvthread_ops_test
./tc_memdom_create_test
./tc_memdom_alloc_test
./tc_smv_create_test
./tc_smvthread_create_test
./tc_shared_mm_test
./tc_cond_var_test
./privs_test

elif [ $RUN == "1" ];
then

    gcc -g $SRCDIR/memdom_no_privs_fault.c -o $HOME/memdom_no_privs_test -lsmv -lpthread
    gcc -g $SRCDIR/memdom_grant_revoke_fault.c -o $HOME/memdom_grant_revoke_test -lsmv -lpthread
    gcc -g $SRCDIR/memdom_write_fault.c -o $HOME/memdom_write_fault_test -lsmv -lpthread
    gcc -g $SRCDIR/memdom_write_implies_read.c -o $HOME/memdom_write_implies_read_test -lsmv -lpthread
    gcc -g $SRCDIR/memdom_grant_revoke_write_fault.c -o $HOME/memdom_grant_revoke_write_test -lsmv -lpthread
    gcc -g $SRCDIR/memdom_grant_revoke_main.c -o $HOME/memdom_grant_revoke_main_test -lsmv -lpthread
    gcc -g $SRCDIR/smvthread_multi_fault.c -o $HOME/smvthread_multi_fault_test -lsmv -lpthread
    gcc -g $SRCDIR/per_smv_memdom_fault.c -o $HOME/per_smv_memdom_fault_test -lsmv -lpthread
    
cd $HOME
echo "*** Running Page Fault Tests***"
./memdom_no_privs_test
./memdom_grant_revoke_test
./memdom_write_fault_test
./memdom_write_implies_read_test
./memdom_grant_revoke_write_test
./memdom_grant_revoke_main_test
./smvthread_multi_fault_test
./per_smv_memdom_fault_test

fi
