#!/bin/bash

./pyronia-linux/testing/install_testing_deps
./pyronia-linux/testing/load_test_profile
./pyronia-linux/testing/restart_pyronia

touch /tmp/cam0
touch /tmp/cam1
touch /tmp/cam2
echo "Don't forget to start the test TCP server."
