#!/bin/bash

KERNEL_SRC=/home/pyronia/pyronia-linux
BUILD=/home/pyronia/build/kernel

cd $KERNEL_SRC
make O=$BUILD ARCH=x86_64 menuconfig

echo "===================== [x64-kernel] Compiling kernel image.  ====================="
make O=$BUILD ARCH=x86_64;
if [ $? -eq 0 ]; then
    echo " ====================== Kernel compiled successfully. =========================="
else
    echo " ====================== Kernel failed to compile, check error messages. error code: $? ========================"
    exit $?
fi

sudo make O=$BUILD ARCH=x86_64 modules_install;
if [ $? -eq 0 ]; then
    echo " ================== kernel modules installed successfully. ======================"
else
    echo " ================== kernel modules failed to install, check error messages. error code: $? =============="
    exit $?
fi

sudo make ARCH=x86_64 INSTALL_HDR_PATH=/usr headers_install;
if [ $? -eq 0 ]; then
    echo " ================== kernel headers installed successfully. ======================"
else
    echo " ================== kernel headers failed to install, check error messages. error code: $? =============="
    exit $?
fi

sudo make O=$BUILD ARCH=x86_64 install;
if [ $? -eq 0 ]; then
    echo " ================== kernel image installed successfully. ======================"
else
    echo " ================== kernel image failed to install, check error messages. error code: $? =============="
    exit $?
fi
